sudo: required

services:
  - docker

before_install:
  - docker build -t amdev/deployment-test-docker -f Dockerfile.dev .

script:
  - docker run amdev/deployment-test-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "deploymentTestDocker"
  env: "Deploymenttestdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-903402067160"
  bucket_path: "deploymentTestDocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
